language: scala

sudo: required

scala:
  - "2.12.3"

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

before_install:
  - docker run -p 5672:5672 -d rabbitmq:3
  - docker run --name database  -d -p 9042:9042 cassandra:3
  - sleep 30
  - docker logs database

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

services:
  - docker

sbt_args: -J-XX:ReservedCodeCacheSize=128m

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  hosts:
    - database

notifications:
  slack:
    rooms:
      - carmonit:3QQdQJefQPFgbLa8mYDboFLt#ci-build
