language: scala

sudo: required

scala:
  - "2.12.1"

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

before_install:
  - docker run -p 5672:5672 -d rabbitmq:3
  - docker run -m 512M --memory-swap 512M --name database  -d -p 9042:9042 -v `pwd`/volumes/scylladb/scylla.yaml:/etc/scylla/scylla.yaml scylladb/scylla --developer-mode 1
  - sleep 20
  - docker logs database

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

services:
  - docker

sbt_args: -J-XX:ReservedCodeCacheSize=128m

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  hosts:
    - database

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fe62042a18d5ee7f061
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   always  # options: [always|never|change] default: always

