version: '2.1'
services:
  database:
    hostname: database
    image: scylladb/scylla:1.7-rc2
    command: --developer-mode 1
    restart: always
    mem_limit: 512m
    ports:
      - "9042:9042"
    volumes:
     - ./volumes/scylladb/scylla.yaml:/etc/scylla/scylla.yaml:rw

  rabbit:
    image: rabbitmq:3
    restart: always

  akka1:
    image: dimetron/netserver
    restart: always
    hostname: akka1
    depends_on:
     - database
     - rabbit
    links:
     - database
     - rabbit
    ports:
      - "8081:8080"

  akka2:
    image: dimetron/netserver
    restart: always
    hostname: akka2
    depends_on:
      - database
      - rabbit
    links:
      - database
      - rabbit
    ports:
      - "8082:8080"

  akka3:
    image: dimetron/netserver
    restart: always
    hostname: akka2
    depends_on:
      - database
      - rabbit
    links:
      - database
      - rabbit
    ports:
      - "8083:8080"

  akka4:
    image: dimetron/netserver
    restart: always
    hostname: akka2
    depends_on:
      - database
      - rabbit
    links:
      - database
      - rabbit
    ports:
      - "8084:8080"

  linkerd:
    image: buoyantio/linkerd:1.0.0-rc2
    restart: always
    mem_limit: 512m
    environment:
      - JVM_HEAP_MAX=256m
    command: [/config.yaml]
    restart: always
    hostname: proxy
    depends_on:
     - akka1
     - akka2
     - rabbit
    links:
      - akka1
      - akka2
      - rabbit
    ports:
      - "8080:8080"
      - "9990:9990"
      - "1883:1883"
      - "8883:8883"
      - "5672:5672"
      - "15672:15672"
    volumes:
     - ./volumes/linkerd/disco:/disco
     - ./volumes/linkerd/config.yaml:/config.yaml