admin:
  port: 9990
  ip: 0.0.0.0

namers:
  - kind: io.l5d.fs
    rootDir: /disco

routers:
- protocol: http
  servers:
  - port: 8080
    ip: 0.0.0.0
    maxConcurrentRequests: 400
  dtab: |
    /svc => /#/io.l5d.fs/app
  client:
    loadBalancer:
      kind: ewma
      maxEffort: 4
      decayTimeMs: 1500