admin:
  port: 9990
  ip: 0.0.0.0

namers:
  - kind: io.l5d.fs
    rootDir: /disco

routers:
- protocol: http
  servers:
  - port: 8080
    ip: 0.0.0.0
    maxConcurrentRequests: 1000
  dtab: |
    /svc => /#/io.l5d.fs/app
  responseClassifier:
      kind: io.l5d.retryableRead5XX
  client:
    loadBalancer:
      kind: ewma
      maxEffort: 3
      decayTimeMs: 3000
    failureAccrual:
      kind: io.l5d.successRate
      successRate: 0.9
      requests: 20
      backoff:
        kind: constant
        ms: 10000