admin:
  port: 9990
  ip: 0.0.0.0

namers:
  - kind: io.l5d.fs
    rootDir: /disco

routers:
- protocol: http
  servers:
  - port: 8080
    ip: 0.0.0.0
    maxConcurrentRequests: 900
  client:
    engine:
      kind: netty4
    loadBalancer:
      kind: ewma
      maxEffort: 3
      decayTimeMs: 10000
    retries:
      budget:
        percentCanRetry: 0.5
  label: AkkaCluster
  dtab: |
    /svc => /#/io.l5d.fs/app
  responseClassifier:
    kind: io.l5d.nonRetryable5XX
